
services:
  tomcat:
    build: .
    ports:
      - "8080:8080" # 접속 포트 변경 원할 경우 왼쪽 8080을 수정 (8090 등 원하는 포트로)
    container_name: spring-tomcat # 나중에 서비스 명으로 변경하기
    depends_on:
      - mariadb
    environment:
      - TZ=Asia/Seoul
    networks:
      - backend
      
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: householdledger
      MARIADB_USER: HJH
      MARIADB_PASSWORD: HJH
      TZ: Asia/Seoul
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  mariadb-data:

networks:
  backend:
    driver: bridge