# src/main/resources/application.yml
db:
  mariadb:
    driver: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/householdledger
    username: HJH
    password: HJH
    mapper: classpath*:mapper/mariadb/*.xml
  oracle:
    driver: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db.avgmax.in:1521:xe
    username: HJH
    password: HJH
    mapper: classpath*:mapper/oracle/*.xml
file:
  minio-dev:
    server: http://localhost:9000
    publicUrl: http://minio:9000
    region: us-east-1
    userId: minioadmin
    userPw: minioadmin
    bucketName: food-images
  minio:
    server: https://minio.avgmax.team
    publicUrl: https://minio.avgmax.team
    region: us-east-1
    userId: avgmaxminioadmin
    userPw: avgmaxminioadmin
    bucketName: food-images
  minio-aws:
    server: https://s3.amazonaws.com     # AWS S3 엔드포인트
    region: us-east-1
    userId: <AWS_ACCESS_KEY>
    userPw: <AWS_SECRET_KEY>
    bucketName: your-bucket-name
